###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: generic
install: true
branches:
  only:
    - master
script:
  - set -o errexit
  - wget https://github.com/srp33/ShinyLearner/archive/master.zip
  - unzip master.zip
  - rm -v master.zip
  - cp -v ShinyLearner_VERSION ShinyLearner-master/VERSION
  - cd ShinyLearner-master/
  - BuildTests/all shinylearner_gpu
  - echo "$DOCKER_PASS" | sudo docker login -u="$DOCKER_USER" --password-stdin
  - sudo docker push srp33/shinylearner_gpu:version459
