#!/bin/bash

message="$1"

if [[ "$message" == "" ]]
then
  echo "No commit message was provided."
  exit 1
fi

version=$(./get_sl_version) .
cat travis.yml.template | sed "s|{version}|$version|g" > .travis.yml
cat Dockerfile.template | sed "s|{version}|$version|g" > Dockerfile

#git add .travis.yml
#git add Dockerfile
git add --all --dry-run
#git commit -m "$message"
#git push origin master
