#!/bin/bash

message="$1"

if [[ "$message" == "" ]]
then
  echo "No commit message was provided."
  exit 1
fi

./get_sl_version

version=$(cat VERSION)
cat travis.yml.template | sed "s|{version}|$version|g" > .travis.yml
cat Dockerfile.template | sed "s|{version}|$version|g" > Dockerfile

git add --all
git commit -m "$message"
git push origin master
