#!/bin/bash

repo=$1

currentDir=$(pwd)
tmpDir=/tmp/shinylearner_gpu_build

rm -rf $tmpDir
mkdir -p $tmpDir

cd $tmpDir

wget https://github.com/srp33/$repo/archive/master.zip
unzip master.zip
rm master.zip

cd ${repo}-master
version=$(cat VERSION)

cd $currentDir
rm -rf $tmpDir

echo $version > ${repo}_VERSION
